import { writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { homedir } from 'node:os';
import { join } from 'node:path';

export const LABEL = 'com.worklog.sync';

/**
 * Single-quotes a value for safe embedding in a generated shell script. Paths can
 * contain spaces, and in principle quotes; without this the generated wrapper would
 * be both broken and injectable.
 */
export function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

export function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

export function launchAgentPath(home = homedir()) {
  return join(home, 'Library', 'LaunchAgents', `${LABEL}.plist`);
}

/**
 * launchd runs jobs with a minimal environment: no shell profile, no PATH to speak
 * of, and no expansion of ${CLAUDE_PLUGIN_ROOT}. The wrapper exists so every path is
 * absolute and resolved at install time, and so secrets can be sourced explicitly.
 */
export function buildWrapperScript({ nodePath, syncPath, worklogHome }) {
  return `#!/bin/bash
# Generated by worklog. Regenerated on every scheduler install; edits will be lost.
set -euo pipefail

WORKLOG_HOME=${shellQuote(worklogHome)}
export WORKLOG_HOME

if [ -f "$WORKLOG_HOME/secrets.env" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$WORKLOG_HOME/secrets.env"
  set +a
fi

mkdir -p "$WORKLOG_HOME/logs"
exec ${shellQuote(nodePath)} ${shellQuote(syncPath)} >> "$WORKLOG_HOME/logs/sync.log" 2>&1
`;
}

export function buildPlist({ wrapperPath, hour, minute, worklogHome }) {
  const logs = join(worklogHome, 'logs');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${escapeXml(LABEL)}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${escapeXml(wrapperPath)}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>${Number(hour)}</integer>
    <key>Minute</key><integer>${Number(minute)}</integer>
  </dict>
  <key>StandardOutPath</key><string>${escapeXml(join(logs, 'launchd.out.log'))}</string>
  <key>StandardErrorPath</key><string>${escapeXml(join(logs, 'launchd.err.log'))}</string>
  <key>RunAtLoad</key><false/>
</dict>
</plist>
`;
}

function run(cmd, args) {
  try {
    return { ok: true, out: execFileSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }) };
  } catch (err) {
    return { ok: false, out: `${err.stdout ?? ''}${err.stderr ?? ''}`.trim() || err.message };
  }
}

/**
 * Modern launchctl uses bootstrap/bootout; older macOS uses load/unload. Try the
 * modern form first and fall back, then verify rather than assuming success: on
 * MDM-managed machines registration can silently be refused.
 */
export function loadAgent(plistPath, { exec = run, uid = process.getuid?.() } = {}) {
  const domain = `gui/${uid}`;
  exec('launchctl', ['bootout', `${domain}/${LABEL}`]);   // ignore failure: may not be loaded

  let result = exec('launchctl', ['bootstrap', domain, plistPath]);
  if (!result.ok) result = exec('launchctl', ['load', '-w', plistPath]);

  const check = exec('launchctl', ['print', `${domain}/${LABEL}`]);
  return { loaded: check.ok, detail: check.ok ? 'registered' : (result.out || check.out) };
}

export function unloadAgent(plistPath, { exec = run, uid = process.getuid?.() } = {}) {
  const domain = `gui/${uid}`;
  const bootout = exec('launchctl', ['bootout', `${domain}/${LABEL}`]);
  if (!bootout.ok) exec('launchctl', ['unload', '-w', plistPath]);
  return { ok: true };
}

export function agentStatus({ exec = run, uid = process.getuid?.() } = {}) {
  const check = exec('launchctl', ['print', `gui/${uid}/${LABEL}`]);
  if (!check.ok) return { installed: false };
  const nextRun = /next fire date = (.+)/.exec(check.out)?.[1]?.trim() ?? null;
  return { installed: true, nextRun };
}

/**
 * Writes the wrapper and plist and registers the job. Returns what it wrote so a
 * caller can show the user the exact contents before anything is loaded.
 */
export function installScheduler({
  worklogHome, pluginRoot, hour, minute,
  nodePath = process.execPath, home = homedir(), dryRun = false, load = loadAgent,
}) {
  if (process.platform !== 'darwin') {
    const err = new Error(
      `automatic scheduling is only implemented for macOS (launchd); this is ${process.platform}. `
      + `Add a cron entry manually: 0 ${hour} * * * /bin/bash ${join(worklogHome, 'run_sync.sh')}`,
    );
    err.code = 'WORKLOG_UNSUPPORTED_PLATFORM';
    throw err;
  }

  const wrapperPath = join(worklogHome, 'run_sync.sh');
  const syncPath = join(pluginRoot, 'bin', 'sync.mjs');
  const plistPath = launchAgentPath(home);

  const wrapper = buildWrapperScript({ nodePath, syncPath, worklogHome });
  const plist = buildPlist({ wrapperPath, hour, minute, worklogHome });
  if (dryRun) return { dryRun: true, wrapperPath, plistPath, wrapper, plist };

  mkdirSync(worklogHome, { recursive: true });
  mkdirSync(join(worklogHome, 'logs'), { recursive: true });
  writeFileSync(wrapperPath, wrapper, { mode: 0o700 });

  mkdirSync(join(home, 'Library', 'LaunchAgents'), { recursive: true });
  writeFileSync(plistPath, plist, { mode: 0o644 });

  const result = load(plistPath);
  return { wrapperPath, plistPath, wrapper, plist, ...result };
}

export function uninstallScheduler({ home = homedir(), worklogHome, unload = unloadAgent } = {}) {
  const plistPath = launchAgentPath(home);
  if (existsSync(plistPath)) {
    unload(plistPath);
    rmSync(plistPath, { force: true });
  }
  if (worklogHome) rmSync(join(worklogHome, 'run_sync.sh'), { force: true });
  return { removed: plistPath };
}
